
# 参考：https://skydum.hatenablog.com/entry/2024/05/11/225833

name: pytest with github actions
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install rye
      run: |
        curl -sSfL https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
        export PATH="$HOME/.rye/bin:$PATH"

    - name: Check rye version
      run: |
        rye --version

    - name: activate rye
      run: |
        source $HOME/.rye/env
        rye sync
        source .venv/bin/activate

    - name: Run tests
      run: |
        rye run python -m pytest
